### ISSUE TITLE
Library evaluation tracking issue

### ISSUE THREAD

**Issue by dtolnay** [alexcrichton/flate2-rs#89]
- [x] [Rename internal types to match the public types](https://github.com/alexcrichton/flate2-rs/issues/75)
- [x] [Write usage examples](https://github.com/alexcrichton/flate2-rs/issues/76)
- [x] [Document the GzBuilder panic cases](https://github.com/alexcrichton/flate2-rs/issues/77)
- [x] [Document error conditions in "Errors" sections](https://github.com/alexcrichton/flate2-rs/issues/78)
- [x] [Use distinct Flush types for Compress::compress vs Decompress::decompress](https://github.com/alexcrichton/flate2-rs/issues/79)
- [x] [Publish CI badges for all Tier 1 platforms](https://github.com/alexcrichton/flate2-rs/issues/80)
- [x] [Wire up rustdoc hyperlinks](https://github.com/alexcrichton/flate2-rs/issues/81)
- [x] [Eagerly implement common traits](https://github.com/alexcrichton/flate2-rs/issues/82)
- [x] [All public types should implement Debug](https://github.com/alexcrichton/flate2-rs/issues/83)
- [x] [GzBuilder methods should take Into<Vec<u8>>](https://github.com/alexcrichton/flate2-rs/issues/84)
- [x] [Clarify documentation of GzHeader::mtime](https://github.com/alexcrichton/flate2-rs/issues/85)
- [x] [Method to get mtime of a GzHeader as a datetime](https://github.com/alexcrichton/flate2-rs/issues/86)
- [x] [Explain what a gzip multistream means](https://github.com/alexcrichton/flate2-rs/issues/87)
- [x] [Remove R: Read bounds on structs](https://github.com/alexcrichton/flate2-rs/issues/88)
- [ ] Bump version to 1.0 (after all else)

This is the tracking issue for the [evaluation](https://public.etherpad-mozilla.org/p/rust-crate-eval-flate2) performed by the libs team this week.

**Comment by SirRade** [comment]
Looking at #79, isn't this already done? Isn't the library ready for 1.0?

**Comment by alexcrichton** [comment]
Yep! I just need to get around to actually hitting the button now!

**Comment by alexcrichton** [comment]
Ok, published!
